# Generated by Django 4.1.2 on 2022-10-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("weigth", models.FloatField()),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("Macho", "Male"),
                            ("Fêmea", "Female"),
                            ("Não informado", "Unknow"),
                        ],
                        default="Não informado",
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
