# Generated by Django 4.1.2 on 2022-10-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trait",
            name="animals",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="traits", to="animals.animal"
            ),
        ),
    ]
