# Generated by Django 4.1.2 on 2022-10-11 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_alter_group_animals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="animals",
        ),
    ]
